# Intro to Python: Pandas and NumPy
## OS305 Lunch & Learn Series

This notebook was created by Teri Walker Theresa.M.Walker29.ctr@mail.mil and Brian Jenkins brian.s.jenkins13.ctr@mail.mil on 8JUN2021. 

The purpose notebook is to explain some basic data exploration techniques using the **pandas** & **NumPy** libraries. 

First import the Pandas library. See [here](https://pandas.pydata.org/docs/getting_started/index.html#getting-started) for extensive documentation on Pandas and the included functionality

In [1]:
import pandas as pd
from pandas_profiling import ProfileReport

Let's see what is in our working directory to import. We are looking for the bestsellerswithcategories.csv to work with.

The bash command **ls** lists directory contents.

In [2]:
ls

bestsellerswithcategories.csv  Intro to Python:Pandas and NumPy.ipynb
Intro to Python EDA.html


To read data into a Pandas DataFrame, we use pd.read_csv

In [3]:
book_data = pd.read_csv('bestsellerswithcategories.csv')

Let's take a quick look at the top 5 of our imported data-set

In [4]:
book_data.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [5]:
#Use pandas profiling to do quick Exploratory Data Analysis of imported data-set. 
prof = ProfileReport(book_data)
prof.to_file(output_file='Intro to Python EDA.html')

Summarize dataset:   0%|          | 0/20 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Now we can see a unique count by column using the nunique() function

In [6]:
#summary stats
book_data.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [7]:
book_data.nunique()

Name           351
Author         248
User Rating     14
Reviews        346
Price           40
Year            11
Genre            2
dtype: int64

In [8]:
pd.set_option('max_rows', None)
book_data[['First', 'Last']] = book_data['Author'].str.split(' ', 1, expand=True)
unique_author = book_data[['First', 'Last']].drop_duplicates()
unique_author.sort_values('Last')

First                          Last
457           F.                      A. Hayek
121        Peter                   A. Lillback
160        Mitch                         Albom
269         Eben                     Alexander
123        Giles                       Andreae
398         Mary                   Ann Shaffer
496          Jay                         Asher
399     Margaret                        Atwood
2         Jordan                   B. Peterson
9        Fredrik                       Backman
259    Christina                   Baker Kline
364       Muriel                       Barbery
99       Johanna                       Basford
522        Silly                          Bear
25         Glenn                          Beck
222          Rob                          Bell
281       Golden                         Books
18      Coloring              Books for Adults
203      Anthony                      Bourdain
239      Crispin                         Boyer
390       Sandra                       Boynton
100          Ray                      Bradbury
175        Allie                         Brosh
182          Dan                         Brown
58        Brené                         Brown
475        Dinah                       Bucholz
161         Todd                         Burpo
400     Jonathan                          Cahn
282        Susan                          Cain
63           Rod                      Campbell
354       Thomas                      Campbell
476         Eric                         Carle
297       Tucker                       Carlson
166         Dale                      Carnegie
50       Francis                          Chan
320         Gary                       Chapman
19           Ron                       Chernow
228        Julia                         Child
218        Chris                        Cleave
330           W.                 Cleon Skousen
286       Ernest                         Cline
35     Ta-Nehisi                        Coates
338        Paulo                        Coelho
439          The                 College Board
139          Jim                       Collins
46       Suzanne                       Collins
15         Adult         Coloring Book Designs
8          James                         Comey
313       Steven                     D. Levitt
163           J.                      D. Vance
434        James                       Dashner
531      William                         Davis
360         Drew                       Daywalt
451      Deborah                        Diesen
116           RH                        Disney
20       Anthony                         Doerr
446          Ree                      Drummond
12        Jaycee                        Dugard
453      Charles                        Duhigg
363       Pierre                         Dukan
146       Sherri                 Duskey Rinker
204          Rob                       Elliott
319      Timothy                       Ferriss
504         Tina                           Fey
135      Gillian                         Flynn
538          Ken                       Follett
180        Gayle                        Forman
93          Joel                    Fuhrman MD
431         Chip                        Gaines
165       Joanna                        Gaines
78           Zhi                      Gang Sha
30           Ina                        Garten
232         Adam                     Gasiewski
34          Atul                       Gawande
4       National               Geographic Kids
176    Hopscotch                         Girls
59       Malcolm                      Gladwell
44         David                       Goggins
29         Angie                         Grace
195        David                         Grann
221         John                         Green
315         John                       Grisham
525         Sara                         Gruen
90        Daniel                       H. Pink
296       Justin

By going through the output above, there are **inconsistancies in the names** George R.R. Martin and J.K. Rowling.

Look closely at the names, there is multiple representations of J.K. Rowling. Can you see space inbetween the initials in the first name? 

In [9]:
Rowlings = book_data.loc[book_data['Author'].str.contains("Rowling", case=False)]
Rowlings

Name         Author  \
102  Fantastic Beasts and Where to Find Them: The O...   J.K. Rowling   
153  Harry Potter and the Chamber of Secrets: The I...   J.K. Rowling   
154  Harry Potter and the Cursed Child, Parts 1 & 2...   J.K. Rowling   
155  Harry Potter and the Goblet of Fire: The Illus...  J. K. Rowling   
156  Harry Potter and the Prisoner of Azkaban: The ...   J.K. Rowling   
157  Harry Potter and the Sorcerer's Stone: The Ill...   J.K. Rowling   
159         Harry Potter Paperback Box Set (Books 1-7)  J. K. Rowling   
353                                 The Casual Vacancy   J.K. Rowling   

     User Rating  Reviews  Price  Year    Genre First        Last  
102          4.7     4370     15  2016  Fiction  J.K.     Rowling  
153          4.9    19622     30  2016  Fiction  J.K.     Rowling  
154          4.0    23973     12  2016  Fiction  J.K.     Rowling  
155          4.9     7758     18  2019  Fiction    J.  K. Rowling  
156          4.9     3146     30  2017  Fiction  J.K.     Rowling  
157          4.9    10052     22  2016  Fiction  J.K.     Rowling  
159          4.8    13471     52  2016  Fiction    J.  K. Rowling  
353          3.3     9372     12  2012  Fiction  J.K.     Rowling

We can pull the thread here to see the difference in spellings in the next two cells

In [10]:
book_data[book_data.Author == 'J. K. Rowling']

Name         Author  \
155  Harry Potter and the Goblet of Fire: The Illus...  J. K. Rowling   
159         Harry Potter Paperback Box Set (Books 1-7)  J. K. Rowling   

     User Rating  Reviews  Price  Year    Genre First        Last  
155          4.9     7758     18  2019  Fiction    J.  K. Rowling  
159          4.8    13471     52  2016  Fiction    J.  K. Rowling

In [11]:
book_data[book_data.Author == 'J.K. Rowling']

Name        Author  \
102  Fantastic Beasts and Where to Find Them: The O...  J.K. Rowling   
153  Harry Potter and the Chamber of Secrets: The I...  J.K. Rowling   
154  Harry Potter and the Cursed Child, Parts 1 & 2...  J.K. Rowling   
156  Harry Potter and the Prisoner of Azkaban: The ...  J.K. Rowling   
157  Harry Potter and the Sorcerer's Stone: The Ill...  J.K. Rowling   
353                                 The Casual Vacancy  J.K. Rowling   

     User Rating  Reviews  Price  Year    Genre First     Last  
102          4.7     4370     15  2016  Fiction  J.K.  Rowling  
153          4.9    19622     30  2016  Fiction  J.K.  Rowling  
154          4.0    23973     12  2016  Fiction  J.K.  Rowling  
156          4.9     3146     30  2017  Fiction  J.K.  Rowling  
157          4.9    10052     22  2016  Fiction  J.K.  Rowling  
353          3.3     9372     12  2012  Fiction  J.K.  Rowling

Let's clean this dirty data up by fixing the misspelling of the Author's name. 

In [12]:
book_data.loc[book_data.Author == 'J. K. Rowling', 'Author'] = 'J.K. Rowling'

Make sure all the data is cleaned by rerunning the line above with the correct spelling

In [13]:
book_data[book_data.Author == 'J.K. Rowling']

Name        Author  \
102  Fantastic Beasts and Where to Find Them: The O...  J.K. Rowling   
153  Harry Potter and the Chamber of Secrets: The I...  J.K. Rowling   
154  Harry Potter and the Cursed Child, Parts 1 & 2...  J.K. Rowling   
155  Harry Potter and the Goblet of Fire: The Illus...  J.K. Rowling   
156  Harry Potter and the Prisoner of Azkaban: The ...  J.K. Rowling   
157  Harry Potter and the Sorcerer's Stone: The Ill...  J.K. Rowling   
159         Harry Potter Paperback Box Set (Books 1-7)  J.K. Rowling   
353                                 The Casual Vacancy  J.K. Rowling   

     User Rating  Reviews  Price  Year    Genre First        Last  
102          4.7     4370     15  2016  Fiction  J.K.     Rowling  
153          4.9    19622     30  2016  Fiction  J.K.     Rowling  
154          4.0    23973     12  2016  Fiction  J.K.     Rowling  
155          4.9     7758     18  2019  Fiction    J.  K. Rowling  
156          4.9     3146     30  2017  Fiction  J.K.     Rowling  
157          4.9    10052     22  2016  Fiction  J.K.     Rowling  
159          4.8    13471     52  2016  Fiction    J.  K. Rowling  
353          3.3     9372     12  2012  Fiction  J.K.     Rowling

Let's do the same thing for George Martin

In [14]:
Martin = book_data.loc[book_data['Author'].str.contains("George", case=False)]

In [15]:
book_data.loc[book_data.Author == 'George R. R. Martin', 'Author'] = 'George R.R. Martin'
book_data.loc[book_data['Author'].str.contains("George", case=False)]

Name              Author  \
3                               1984 (Signet Classics)       George Orwell   
5        A Dance with Dragons (A Song of Ice and Fire)  George R.R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R.R. Martin   
67                                     Decision Points      George W. Bush   
118  Game of Thrones Boxed Set: A Game of Thrones/A...  George R.R. Martin   
119  Game of Thrones Boxed Set: A Game of Thrones/A...  George R.R. Martin   
120  Game of Thrones Boxed Set: A Game of Thrones/A...  George R.R. Martin   

     User Rating  Reviews  Price  Year        Genre   First          Last  
3            4.7    21424      6  2017      Fiction  George        Orwell  
5            4.4    12643     11  2011      Fiction  George  R. R. Martin  
6            4.7    19735     30  2014      Fiction  George  R. R. Martin  
67           4.6     2137     17  2010  Non Fiction  George       W. Bush  
118          4.6     5594      5  2011      Fiction  George   R.R. Martin  
119          4.6     5594      5  2012      Fiction  George   R.R. Martin  
120          4.6     5594      5  2013      Fiction  George   R.R. Martin

Select specific columns from a dataframe. Each column in a DataFrame is a Series. As a single column is selected, the returned object is a pandas Series. 

In [16]:
genre = book_data["Genre"]
genre.head()

0    Non Fiction
1        Fiction
2    Non Fiction
3        Fiction
4    Non Fiction
Name: Genre, dtype: object

Verify Series by checking:

In [17]:
type(book_data["Genre"])

pandas.core.series.Series

We used the shape attribute before, now lets use the count function to count the rows. 

*Note: count() only counts the non-NA cells. (None, NaN, NaT are all considered NA). You will need to make sure you examine your data closely so you don't get unexpected count.*

In [18]:
book_data["Genre"].count()

550

How many Fiction vs Non-Fiction are in the data-set

In [19]:
book_data["Genre"].value_counts()

Non Fiction    310
Fiction        240
Name: Genre, dtype: int64

Grab multiple columns (subset of data)

In [20]:
#First, restate the column names so we don't have to scroll back up to the top
print(book_data.columns.values)

['Name' 'Author' 'User Rating' 'Reviews' 'Price' 'Year' 'Genre' 'First'
 'Last']


In [21]:
book_reviews = book_data[["Name", "Author", "Genre", "Year"]]
book_reviews.tail()

Name       Author  \
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)  Jeff Kinney   
546  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

           Genre  Year  
545      Fiction  2019  
546  Non Fiction  2016  
547  Non Fiction  2017  
548  Non Fiction  2018  
549  Non Fiction  2019

We now have a DataFrame

In [22]:
type(book_reviews)

pandas.core.frame.DataFrame

Let's focus on our fiction best sellers

In [23]:
book_fiction = book_reviews.loc[book_reviews["Genre"] == "Fiction"]
book_fiction.count()

Name      240
Author    240
Genre     240
Year      240
dtype: int64

Use the loc[] attribute to look at a specific row.

*Note: is primarily label based, but may also be used with a boolean array. You can use df.iloc to access a group of rows and columns by integer position(s).*

In [24]:
book_reviews.loc[470]

Name      The Time Traveler's Wife
Author          Audrey Niffenegger
Genre                      Fiction
Year                          2009
Name: 470, dtype: object

## For more information on the difference between functions and attributes in pandas, look [here](https://www.geeksforgeeks.org/difference-between-attributes-and-properties-in-python/) 

Let's sort by Year and Author

In [25]:
book_fiction.sort_values(by=['Year']).head(5)

Name              Author  \
470                           The Time Traveler's Wife  Audrey Niffenegger   
398  The Guernsey Literary and Potato Peel Pie Society    Mary Ann Shaffer   
388  The Girl with the Dragon Tattoo (Millennium Se...       Stieg Larsson   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)         Jeff Kinney   
364                       The Elegance of the Hedgehog      Muriel Barbery   

       Genre  Year  
470  Fiction  2009  
398  Fiction  2009  
388  Fiction  2009  
72   Fiction  2009  
364  Fiction  2009

Let's look at all fiction books published in 2009

In [26]:
book_2009 = book_fiction[book_fiction.Year.isin([2009])] 
book_2009

Name              Author  \
38           Breaking Dawn (The Twilight Saga, Book 4)     Stephenie Meyer   
60   Dead And Gone: A Sookie Stackhouse Novel (Sook...    Charlaine Harris   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)         Jeff Kinney   
80   Dog Days (Diary of a Wimpy Kid, Book 4) (Volum...         Jeff Kinney   
95                            Eclipse (Twilight Sagas)     Stephenie Meyer   
96                                  Eclipse (Twilight)     Stephenie Meyer   
177                                      I, Alex Cross     James Patterson   
241                       New Moon (The Twilight Saga)     Stephenie Meyer   
254                                   Olive Kitteridge    Elizabeth Strout   
299                                  Sookie Stackhouse    Charlaine Harris   
364                       The Elegance of the Hedgehog      Muriel Barbery   
387         The Girl Who Played with Fire (Millennium)       Stieg Larsson   
388  The Girl with the Dragon Tattoo (Millennium Se...       Stieg Larsson   
398  The Guernsey Literary and Potato Peel Pie Society    Mary Ann Shaffer   
402                                           The Help    Kathryn Stockett   
418  The Last Olympian (Percy Jackson and the Olymp...        Rick Riordan   
429                                    The Lost Symbol           Dan Brown   
459        The Shack: Where Tragedy Confronts Eternity    William P. Young   
470                           The Time Traveler's Wife  Audrey Niffenegger   
473                       The Twilight Saga Collection     Stephenie Meyer   
513               Twilight (The Twilight Saga, Book 1)     Stephenie Meyer   
520                            Under the Dome: A Novel        Stephen King   
524                                           Watchmen          Alan Moore   
535                          Where the Wild Things Are      Maurice Sendak   

       Genre  Year  
38   Fiction  2009  
60   Fiction  2009  
72   Fiction  2009  
80   Fiction  2009  
95   Fiction  2009  
96   Fiction  2009  
177  Fiction  2009  
241  Fiction  2009  
254  Fiction  2009  
299  Fiction  2009  
364  Fiction  2009  
387  Fiction  2009  
388  Fiction  2009  
398  Fiction  2009  
402  Fiction  2009  
418  Fiction  2009  
429  Fiction  2009  
459  Fiction  2009  
470  Fiction  2009  
473  Fiction  2009  
513  Fiction  2009  
520  Fiction  2009  
524  Fiction  2009  
535  Fiction  2009

Use the count function to return how many 2009 published books are returned

In [27]:
book_2009.count()

Name      24
Author    24
Genre     24
Year      24
dtype: int64

In [44]:
non_fiction_2009 = book_data[(book_data['Year'].isin(['2009'])) & (book_data['Genre'] == 'Non Fiction')]
non_fiction_2009

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  \
0                  JJ Smith          4.7    17350      8  2016  Non Fiction   
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   
5        George R.R. Martin          4.4    12643     11  2011      Fiction   

      First             Last  
0        JJ            Smith  
1   Stephen             King  
2    Jordan      B. Peterson  
3    George           Orwell  
4  National  Geographic Kids  
5    George     R. R. Martin

**REMEMBER**

When selecting subsets of data, square brackets [] are used.

- Inside these brackets, you can use a single column/row label, a list of column/row labels, a slice of labels, a conditional expression or a colon.

- Select specific rows and/or columns using loc when using the row and column names

- Select specific rows and/or columns using iloc when using the positions in the table

- You can assign new values to a selection based on loc/iloc.

# Using NumPy to further examine the data

For more information NumPy, look [here](https://numpy.org/doc/stable/) 

Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations. For example, you can divide each element of an array by the same number with just one line of code.

In [28]:
#import numpy package
import numpy as np

Create two seperate arrays and doing addition of arrays

In [29]:
#define np1
np1 = np.array([1,2,3])
np1
#define np2
np2 = np.array([2,3,4])
np2
#addition
np1 + np2

array([3, 5, 7])

Be careful, don't always get the answer you expect.

In [30]:
[1,2,3]+[2,3,4]

[1, 2, 3, 2, 3, 4]

Another way to do addition

In [31]:
np.array([1,2,3])+np.array([2,3,4])

array([3, 5, 7])

More math with arrays

In [32]:
np1-np2

array([-1, -1, -1])

In [33]:
np1*np2

array([ 2,  6, 12])

In [34]:
np1/np2

array([0.5       , 0.66666667, 0.75      ])

Let's go back to the bestsellers example 

In [35]:
#put User Ratings into an array for further exploration
ratings = book_data['User Rating'].values

In [36]:
ratings

array([4.7, 4.6, 4.7, 4.7, 4.8, 4.4, 4.7, 4.7, 4.7, 4.6, 4.6, 4.6, 4.6,
       4.5, 4.6, 4.5, 4.6, 4.4, 4.5, 4.8, 4.6, 4.6, 3.9, 4.6, 4.3, 4.6,
       4.7, 4.2, 4.6, 4.6, 4.8, 4.7, 4.8, 4.8, 4.8, 4.7, 4.7, 4.7, 4.6,
       4.5, 4.9, 4.9, 4.8, 4.6, 4.8, 4.5, 4.7, 4.7, 4.7, 4.7, 4.7, 4.7,
       4.7, 4.3, 4.8, 4.8, 4.6, 4.6, 4.8, 4.4, 4.6, 4.3, 4.2, 4.8, 4.8,
       4.8, 4.8, 4.6, 4.6, 4.5, 4.5, 4.8, 4.8, 4.8, 4.6, 4.6, 4.6, 4.5,
       4.6, 4.7, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 4.8, 4.6, 4.5,
       4.5, 4.3, 4.5, 4.5, 4.7, 4.7, 4.7, 4.7, 4.7, 4.6, 4.6, 4.7, 4.4,
       4.4, 4.5, 3.8, 3.8, 4.5, 4.2, 4.7, 4.7, 4.7, 4.7, 4.7, 4.4, 4.7,
       4.4, 4.6, 4.6, 4.6, 4.5, 4.6, 4.8, 4.8, 4.8, 4.8, 4.8, 4.6, 4.6,
       4.6, 4.6, 3.6, 4.8, 4.6, 4. , 4. , 4. , 4.6, 4.5, 4.5, 4.5, 4.5,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.6, 4.4, 4.8, 4.9, 4.8, 4.9, 4. , 4.9,
       4.9, 4.9, 4.7, 4.8, 4.8, 4.7, 4.7, 4.4, 4.4, 4.8, 4.7, 4.7, 4.7,
       4.7, 4.7, 4.3, 4.8, 4.8, 4.9, 4.7, 4.8, 4.6, 4.8, 4.8, 4.

In [37]:
#what is the highest Rating in this array?
np.max(ratings)

4.9

In [38]:
#how many seperate ratings are 3.5 >< 4.5
ratings[(ratings>3.5) & (ratings<4.5)].shape

(97,)

In [39]:
#Look at how many unique authors are in data-set
author = book_data['Author'].values
np.unique(author).shape[0]

246

In [40]:
#Find the mean value of all the Reviews
reviews = book_data['Reviews'].values
np.mean(reviews)

11953.281818181818

In [41]:
#Find the index where Author is Julia Child
np.where(author == 'Julia Child')

(array([228]),)

In [42]:
#Julia Child is found in index # 228. Let's see it using pandas
book_data.loc[228]

Name           Mastering the Art of French Cooking, Vol. 2
Author                                         Julia Child
User Rating                                            4.8
Reviews                                               2926
Price                                                   27
Year                                                  2009
Genre                                          Non Fiction
First                                                Julia
Last                                                 Child
Name: 228, dtype: object

## There is **SO** much more you can do with pandas and NumPy. Today, we just scratched the surface. 

Take a look [here](https://www.w3schools.com/python/numpy/default.asp) for some extra readings and tutorials on NumPy.

Thank you for joining us today!